### ISSUE TITLE
fail to display help

### ISSUE THREAD

**Issue by gilcot** [LaserPhaser/gitlab-group-clone#1]
Hello Arseni

I was able to install your contribution
```
gilcot@localhost $ pip install gitlab-clone
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Defaulting to user installation because normal site-packages is not writeable
Collecting gitlab-clone
  Using cached gitlab_clone-0.1.3-py2.py3-none-any.whl (4.3 kB)
Requirement already satisfied: requests in /Users/gilcot/Library/Python/2.7/lib/python/site-packages (from gitlab-clone) (2.23.0)
Requirement already satisfied: idna<3,>=2.5 in /Users/gilcot/Library/Python/2.7/lib/python/site-packages (from requests->gitlab-clone) (2.9)
Requirement already satisfied: chardet<4,>=3.0.2 in /Users/gilcot/Library/Python/2.7/lib/python/site-packages (from requests->gitlab-clone) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /Users/gildascotomale/Library/Python/2.7/lib/python/site-packages (from requests->gitlab-clone) (1.25.9)
Requirement already satisfied: certifi>=2017.4.17 in /Users/gildcot/Library/Python/2.7/lib/python/site-packages (from requests->gitlab-clone) (2020.4.5.1)
Installing collected packages: gitlab-clone
Successfully installed gitlab-clone-0.1.3
```
But I can't make it work
```
gilcot@localhost $ gitlab-clone -h
Traceback (most recent call last):
  File "/Users/gilcot/Library/Python/2.7/bin/gitlab-clone", line 5, in <module>
    from gitlab_clone.clonner import main
  File "/Users/gilcot/Library/Python/2.7/lib/python/site-packages/gitlab_clone/clonner.py", line 30
    f"https://{gitlab_url}/api/v4/groups/{group_id}/projects?private_token={token}&include_subgroups=True&per_page=100&page={page}&with_shared=False")
                                                                                                                                                    ^
SyntaxError: invalid syntax
```
It seems to be related to argument parsing, but I may be wrong.

**Comment by LaserPhaser** [comment]
It's because you are using python 2.7 and i'm using F-strings.
Please use python 3, cause python 2 is EOL)

**Comment by gilcot** [comment]
Many thanks for your reply. I removed it and reinstall it with Python3
```
gilcot@localhost $ pip3 install gitlab-clone
Defaulting to user installation because normal site-packages is not writeable
Collecting gitlab-clone
  Using cached gitlab_clone-0.1.3-py2.py3-none-any.whl (4.3 kB)
Collecting requests
  Using cached requests-2.23.0-py2.py3-none-any.whl (58 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2020.4.5.1-py2.py3-none-any.whl (157 kB)
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1
  Using cached urllib3-1.25.9-py2.py3-none-any.whl (126 kB)
Collecting idna<3,>=2.5
  Using cached idna-2.9-py2.py3-none-any.whl (58 kB)
Collecting chardet<4,>=3.0.2
  Using cached chardet-3.0.4-py2.py3-none-any.whl (133 kB)
Installing collected packages: certifi, urllib3, idna, chardet, requests, gitlab-clone
Successfully installed certifi-2020.4.5.1 chardet-3.0.4 gitlab-clone-0.1.3 idna-2.9 requests-2.23.0 urllib3-1.25.9
```
Now having some strange thing, but I've been able to overcome it.
```
gilcot@localhost $ gitlab-clone -h 
-bash: /Users/gilcot/Library/Python/2.7/bin/gitlab-clone: No such file or directory
gilcot@localhost $ /Users/gilcot/Library/Python/3.7/bin/gitlab-clone -h
usage: gitlab-clone [-h] --group_id group_id --token token [--branch branch]
                    [--gitlab-url gitlab]

Required args for recursive clone

optional arguments:
  -h, --help           show this help message and exit
  --group_id group_id  Id of a group in gitlab
  --token token        Gitlab Token
  --branch branch      Branch to clone in all repos [by default master]
  --gitlab-url gitlab  Gitlab address [by default gitlab.com]
```
I'll do with that or add an alias.

It's a pity PIP doesn't deal with Python version requirement. However, you should mention the minimum version needed and the versions you tested against.

Regards.

**Comment by LaserPhaser** [comment]
@gilcot sure I will add min python version to the reqs.
What's the kind of "some strange thing" did you have

**Comment by gilcot** [comment]
Hello @ArseniyAntonov 

The strange thing I had, was that autocomplete did work, but it wasn't finding the right path. 
```
gilcot@localhost $ gitlab-clone -h 
-bash: /Users/gilcot/Library/Python/2.7/bin/gitlab-clone: No such file or directory
gilcot@localhost $ /Users/gilcot/Library/Python/3.7/bin/gitlab-clone -h
usage: gitlab-clone [-h] --group_id group_id --token token [--branch branch]
                    [--gitlab-url gitlab]

Required args for recursive clone

optional arguments:
  -h, --help           show this help message and exit
  --group_id group_id  Id of a group in gitlab
  --token token        Gitlab Token
  --branch branch      Branch to clone in all repos [by default master]
  --gitlab-url gitlab  Gitlab address [by default gitlab.com]
```
Finally I found why
```
gilcot@localhost $ type gitlab-clone
gitlab-clone is hashed (/Users/gilcot/Library/Python/2.7/bin/gitlab-clone)
```
It should be corrected if I relog again, but I never logout… For now, I've make an alias 

Will open another issue later for something else.
